org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false
fabric.loom.dropNonIntermediateRootMethods=true

mod.id=eg_precise_fps
mod.name=Precise FPS
mod.description=Multi-version, multi-loader mod template for Minecraft using Stonecutter.
mod.group=games.enchanted
mod.version=1.0.0
mod.license=MIT
mod.source_url=https://github.com/Enchanted-Games/enchanteds-mod-template
mod.issue_tracker=https://github.com/Enchanted-Games/enchanteds-mod-template/issues
mod.icon=assets/eg_precise_fps/icon.png

deps.minecraft=[VERSIONED]
dep_str.minecraft=[VERSIONED]

deps.fabric-loader=0.18.5
dep_str.fabric-loader=>=0.18

deps.fabric-api=[VERSIONED]
dep_str.fabric-api=[VERSIONED]

deps.neoforge=[VERSIONED]

publish.dry_run=true
# Uncomment and enter modrinth or curseforge project ids to enable publishing
#publish.modrinth=
#publish.curseforge=
#publish.additionalVersions=[VERSIONED]